:sparkles: Fail CI if JavaDoc is missing like in zosma
delta-leonis/torch pull request #9
Opened 2017-10-31 21:55 UTC by ThomasHakkers

2017-10-31 22:00 UTC, thumbnail requested changes
As we can see in [circleci](https://circleci.com/gh/delta-leonis/torch/46?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) it works! 
Bad news is you'll need to fix the javadoc in either a separate issue; or in this one.

2017-11-09 19:16 UTC, RyanMeulenkamp approved these changes

2017-11-09 19:22 UTC, thumbnail submitted a review, later dismissed

2017-11-09 19:30 UTC, thumbnail approved these changes
I hereby allow my own changes.

2017-11-09 19:31 UTC, merged